#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BLUE='\033[0;34m'
GREEN='\033[0;32m'

yarn run test:ci && yarn run lint && yarn check:types && yarn check:audit && yarn check:outdated

echo -e "${BLUE}#########################################################"
echo -e "${BLUE}##     OUTDATED DEPENDENCIES PRINTED FOR INFO          ##"
echo -e "${BLUE}#########################################################"

# Branch prefix validation
branch_name=$(git rev-parse --abbrev-ref HEAD)
pattern="^(feature|build|chore|fix|release|docs|refactor|test)/"

if [[ ! $branch_name =~ $pattern ]]; then
  echo "Error: Branch name must start with one of 'feature/', 'build/', 'chore/', 'fix/', 'release/', 'docs/', 'refactor/', 'test/'"
  echo "Your branch name is: $branch_name"
  exit 1
fi

echo -e "${GREEN}# ALL PRE-PUSH CHECKS PASSED #"